"use client";

type Props = {
  filename: string;
};

export default function VideoCard({
  filename,
}: Props) {
  const videoUrl =
    `http://127.0.0.1:8000/exports/${encodeURIComponent(filename)}`;

  const handleDownload = async () => {
    try {
      const response = await fetch(videoUrl);

      if (!response.ok) {
        throw new Error("Video download failed");
      }

      const blob = await response.blob();

      const blobUrl = window.URL.createObjectURL(blob);

      const link = document.createElement("a");

      link.href = blobUrl;
      link.download = filename;

      document.body.appendChild(link);

      link.click();

      link.remove();

      window.URL.revokeObjectURL(blobUrl);
    } catch (error) {
      console.error("Download error:", error);

      alert("Videoni yuklab bo'lmadi.");
    }
  };

  return (
    <div
      className="
        group
        overflow-hidden
        rounded-3xl
        border
        border-zinc-800
        bg-zinc-950
        shadow-xl
        shadow-black/20
        transition-all
        duration-300
        hover:-translate-y-1
        hover:border-violet-500/30
        hover:shadow-violet-950/20
      "
    >
      {/* VIDEO */}
      <div className="relative overflow-hidden bg-black">
        <video
          controls
          preload="metadata"
          className="
            aspect-[9/16]
            w-full
            bg-black
            object-cover
          "
        >
          <source
            src={videoUrl}
            type="video/mp4"
          />

          Your browser does not support the video tag.
        </video>

        {/* AI BADGE */}
        <div
          className="
            pointer-events-none
            absolute
            left-3
            top-3
            rounded-lg
            border
            border-violet-400/20
            bg-black/70
            px-2.5
            py-1.5
            text-[11px]
            font-black
            uppercase
            tracking-wider
            text-violet-300
            backdrop-blur-md
          "
        >
          AI Generated
        </div>
      </div>

      {/* INFO */}
      <div className="p-5">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <h3 className="truncate text-sm font-bold text-white">
              {filename}
            </h3>

            <p className="mt-1 text-xs text-zinc-600">
              Generated by ClipForge AI
            </p>
          </div>

          <div
            className="
              flex
              h-8
              w-8
              shrink-0
              items-center
              justify-center
              rounded-lg
              bg-violet-600/10
              text-sm
            "
          >
            ✨
          </div>
        </div>

        {/* BUTTONS */}
        <div className="mt-5 grid grid-cols-2 gap-3">
          {/* PREVIEW */}
          <a
            href={videoUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="
              rounded-xl
              border
              border-zinc-800
              bg-zinc-900
              py-2.5
              text-center
              text-sm
              font-bold
              text-white
              transition-all
              duration-200
              hover:border-violet-500/40
              hover:bg-zinc-800
            "
          >
            Preview
          </a>

          {/* DOWNLOAD */}
          <button
            type="button"
            onClick={handleDownload}
            className="
              rounded-xl
              bg-gradient-to-r
              from-violet-600
              to-fuchsia-600
              py-2.5
              text-sm
              font-bold
              text-white
              shadow-lg
              shadow-violet-900/20
              transition-all
              duration-200
              hover:-translate-y-0.5
              hover:shadow-violet-900/40
              active:translate-y-0
            "
          >
            Download
          </button>
        </div>
      </div>
    </div>
  );
}