"use client";

import { useState } from "react";

type Props = {
  filename: string;
};

export default function VideoCard({
  filename,
}: Props) {
  const [downloading, setDownloading] =
    useState(false);

  const videoUrl =
    `http://127.0.0.1:8000/exports/${encodeURIComponent(
      filename
    )}`;

  const handleDownload = async () => {
    if (downloading) return;

    try {
      setDownloading(true);

      const response =
        await fetch(videoUrl);

      if (!response.ok) {
        throw new Error(
          "Video download failed"
        );
      }

      const blob =
        await response.blob();

      const blobUrl =
        window.URL.createObjectURL(
          blob
        );

      const link =
        document.createElement("a");

      link.href = blobUrl;
      link.download = filename;

      document.body.appendChild(
        link
      );

      link.click();

      link.remove();

      window.URL.revokeObjectURL(
        blobUrl
      );
    } catch (error) {
      console.error(
        "Download error:",
        error
      );

      alert(
        "Videoni yuklab bo'lmadi."
      );
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div
      className="
        group
        overflow-hidden
        rounded-3xl
        border
        border-zinc-800
        bg-[#111113]
        shadow-xl
        shadow-black/20
        transition-all
        duration-300
        hover:-translate-y-1
        hover:border-violet-500/30
        hover:shadow-2xl
        hover:shadow-violet-950/20
      "
    >
      {/* VIDEO */}
      <div
        className="
          relative
          aspect-[9/16]
          overflow-hidden
          bg-black
        "
      >
        <video
          src={videoUrl}
          controls
          preload="metadata"
          playsInline
          className="
            h-full
            w-full
            object-cover
            transition-transform
            duration-500
            group-hover:scale-[1.02]
          "
        >
          Your browser does not support
          the video tag.
        </video>

        {/* TOP GRADIENT */}
        <div
          className="
            pointer-events-none
            absolute
            inset-x-0
            top-0
            h-28
            bg-gradient-to-b
            from-black/70
            to-transparent
          "
        />

        {/* AI BADGE */}
        <div
          className="
            pointer-events-none
            absolute
            left-3
            top-3
            flex
            items-center
            gap-1.5
            rounded-xl
            border
            border-violet-400/20
            bg-black/65
            px-3
            py-1.5
            text-[10px]
            font-black
            uppercase
            tracking-widest
            text-violet-300
            backdrop-blur-xl
          "
        >
          <span className="text-xs">
            ✨
          </span>

          AI Generated
        </div>

        {/* NUMBER / STATUS */}
        <div
          className="
            pointer-events-none
            absolute
            right-3
            top-3
            rounded-xl
            border
            border-emerald-400/20
            bg-black/65
            px-3
            py-1.5
            text-[10px]
            font-bold
            uppercase
            tracking-wider
            text-emerald-400
            backdrop-blur-xl
          "
        >
          Ready
        </div>
      </div>

      {/* INFO */}
      <div className="p-5">
        {/* HEADER */}
        <div
          className="
            flex
            items-start
            justify-between
            gap-3
          "
        >
          <div className="min-w-0">
            <p
              className="
                mb-1
                text-[10px]
                font-bold
                uppercase
                tracking-widest
                text-violet-400
              "
            >
              Short Video
            </p>

            <h3
              title={filename}
              className="
                truncate
                text-sm
                font-bold
                text-white
              "
            >
              {filename}
            </h3>

            <p
              className="
                mt-1.5
                text-xs
                text-zinc-600
              "
            >
              Generated by ClipForge AI
            </p>
          </div>

          {/* ICON */}
          <div
            className="
              flex
              h-9
              w-9
              shrink-0
              items-center
              justify-center
              rounded-xl
              border
              border-violet-500/10
              bg-violet-600/10
              text-sm
              transition
              duration-300
              group-hover:bg-violet-600/20
            "
          >
            ✨
          </div>
        </div>

        {/* DIVIDER */}
        <div
          className="
            my-5
            h-px
            bg-zinc-800/80
          "
        />

        {/* BUTTONS */}
        <div
          className="
            grid
            grid-cols-2
            gap-3
          "
        >
          {/* PREVIEW */}
          <a
            href={videoUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="
              flex
              items-center
              justify-center
              gap-2
              rounded-xl
              border
              border-zinc-800
              bg-zinc-900
              py-3
              text-sm
              font-bold
              text-zinc-200
              transition-all
              duration-200
              hover:border-zinc-700
              hover:bg-zinc-800
              hover:text-white
            "
          >
            <span>▶</span>
            Preview
          </a>

          {/* DOWNLOAD */}
          <button
            type="button"
            onClick={
              handleDownload
            }
            disabled={downloading}
            className="
              flex
              items-center
              justify-center
              gap-2
              rounded-xl
              bg-gradient-to-r
              from-violet-600
              to-fuchsia-600
              py-3
              text-sm
              font-bold
              text-white
              shadow-lg
              shadow-violet-900/20
              transition-all
              duration-200
              hover:-translate-y-0.5
              hover:shadow-xl
              hover:shadow-violet-900/30
              active:translate-y-0
              disabled:cursor-not-allowed
              disabled:opacity-60
              disabled:hover:translate-y-0
            "
          >
            {downloading ? (
              <>
                <span
                  className="
                    h-4
                    w-4
                    animate-spin
                    rounded-full
                    border-2
                    border-white/30
                    border-t-white
                  "
                />

                Downloading...
              </>
            ) : (
              <>
                <span>↓</span>
                Download
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}